sudo: required
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.13.0
  - jruby-head
  - ruby-head
matrix:
  include:
    - rvm: rubinius-3
      env:
        - RUBYOPT="-rbundler/deprecate"
  allow_failures:
    - rvm: jruby-9.1.13.0
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius-3
before_install:
  - gem update --system
branches:
  only:
    - master
